# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            andysigler
tagline:          make useless things
url:              http://www.andysigler.com
paginate:         20
baseurl:          /
author:			  Andy Sigler
name:           Andy Sigler
email:          andrewsigler1@gmail.com